Feature/update edit profile form
CiviWiki/OpenCiviWiki pull request #1005
Opened 2021-09-11 16:07 UTC by wassafshahzad

What does this PR do ?

- This PR removes The Edit profile form and renders a read only settings forms.
- This PR fixes an issue where a new user is unable to setup  account.
- This PR makes the setting form reusable.

Images
![Profile](https://user-images.githubusercontent.com/25094157/132954084-1f553750-13cb-4fe8-831c-209563ee459b.png)

2021-09-12 17:32 UTC, alanCalvillo-Wizeline commented
The code looks good, is it possible to have some sort of basic unit testing for this new update that you are including in the project ?

2021-09-12 18:36 UTC, wassafshahzad commented
> The code looks good, is it possible to have some sort of basic unit testing for this new update that you are including in the project ?

Yeah i could add test for the forms and the view . if that is ok

2021-09-13 08:55 UTC, brylie commented
@all-contributors please add @alanCalvillo-Wizeline for review

2021-09-13 09:52 UTC, brylie requested changes
As per @wassafshahzad's feedback

> The code looks good, is it possible to have some sort of basic unit testing for this new update that you are including in the project ?

2021-09-14 07:14 UTC, brylie commented on project/accounts/templates/accounts/utils/update_settings_form.html
> +            Account Settings
```suggestion
            Profile
```

2021-09-14 07:15 UTC, brylie approved these changes

2021-09-14 07:15 UTC, brylie commented on project/threads/templates/threads/partials/account/account_base.html
> +                                <a href="#settings">SETTINGS</a>
```suggestion
                                <a href="#settings">Settings</a>
```

2021-09-14 07:15 UTC, brylie approved these changes

2021-09-14 07:15 UTC, merged