Thread restructuring
CiviWiki/OpenCiviWiki pull request #1048
Opened 2021-09-28 06:13 UTC by AbhijithGanesh

Works on #1032

2021-09-28 06:13 UTC, pep8speaks commented
Hello @AbhijithGanesh! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`project/threads/api.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/api.py):

> [Line 28:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/api.py#L28): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 177:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/api.py#L177): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 413:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/api.py#L413): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 509:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/api.py#L509): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`project/threads/models.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/models.py):

> [Line 9:38](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/models.py#L9): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 385:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/models.py#L385): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 472:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/models.py#L472): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 491:1](https://github.com/CiviWiki/OpenCiviWiki/blob/651badaa7b9f24ded7bf6febd6b2a76520863cdb/project/threads/models.py#L491): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-09-28 09:51 UTC, brylie requested changes

2021-09-28 09:51 UTC, brylie commented on project/threads/utils.py
> +
This is related to `accounts` so can be deleted from your pull request.
```suggestion
```

2021-09-28 09:54 UTC, brylie requested changes
Great work so far! Pretty much all we need are the serializers and database migrations :sunglasses:

2021-09-28 11:08 UTC, AbhijithGanesh commented
Atleast then I don't need to rebase again😂. I was kind of disappointed at first but then understood the purpose of it.

2021-09-28 11:53 UTC, AbhijithGanesh commented
@brylie please review this, excluding PEP 8 Changes, are there changes I need to make?

2021-09-28 15:43 UTC, brylie commented
@AbhijithGanesh are you able to resolve the conflicts in this branch? If not, you can grant me write access and I can help out. I'm a bit tired tonight but might be able to help out in a day or so.

2021-09-28 15:43 UTC, AbhijithGanesh commented
I can't see the conflicts

2021-09-28 15:46 UTC, brylie commented
![image](https://user-images.githubusercontent.com/17307/135121072-c7605d36-c8c3-4afb-8d61-124b14c5d6fb.png)

It shows the list of conflicts below the conversation.

2021-09-28 15:48 UTC, brylie commented
These instructions might be helpful: 

https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

2021-09-28 15:49 UTC, AbhijithGanesh commented
I can't resolve/ view the conflicts here because only the ones with write access can see, I shall do it on my fork though

2021-09-28 16:05 UTC, AbhijithGanesh commented
Resolved it.

2021-09-28 16:06 UTC, gorkemarslan commented
Because the project has constantly been changed and you are the one who is unlucky. Your task is more difficult than ours and prone to conflicting. In the end, it is inevitable to have so many conflicts.

I really understand your situation because trying, starting from the very beginning, again and again, makes you exhausted.

So congratulations and big thanks for your effort. :)

2021-09-28 16:07 UTC, gorkemarslan commented
@AbhijithGanesh, could you take a look at the last line of the test?

`ImportError: cannot import name 'get_account' from 'threads.utils' (/home/runner/work/OpenCiviWiki/OpenCiviWiki/project/threads/utils.py)`

2021-09-28 16:19 UTC, brylie commented on project/accounts/api.py
> +from threads.utils import get_account, json_response
This should fix the error mentioned by @gorkemarslan 

```suggestion
from api.utils import get_account
from threads.utils import json_response
```

2021-09-28 16:21 UTC, brylie commented on project/threads/permissions.py
> +from .utils import get_account
Related to error mentioned by @gorkemarslan 

```suggestion
from api.utils import get_account
```

2021-09-28 16:23 UTC, brylie commented
@AbhijithGanesh perhaps the `get_account` function should be moved to `core/utils.py`. Then, the files that use `get_account` can be updated with the following import:

```py
from core.utils import get_account
```

2021-09-28 16:25 UTC, brylie requested changes

2021-09-28 16:25 UTC, brylie commented on project/threads/utils.py
> -
Let's move this function to `account/utils.py` since it is related to accounts. Then, do a search for all files that use `get_account`  and add the correct import:

```py
from accounts.utils import get_account
```

2021-09-28 16:33 UTC, AbhijithGanesh commented on project/threads/utils.py
> -
I will make the changes

2021-09-28 16:42 UTC, AbhijithGanesh commented on project/threads/utils.py
> -
@brylie Please check

2021-09-28 17:08 UTC, gorkemarslan requested changes

2021-09-28 17:08 UTC, gorkemarslan commented on project/accounts/api.py
> +from accounts.utils import get_account, json_response
```suggestion
from threads.utils import json_response
from accounts.utils import get_account
```

`json_response` is in the `threads.utils` file not in the `accounts.utils`.

2021-09-28 17:28 UTC, gorkemarslan requested changes

2021-09-28 17:28 UTC, gorkemarslan commented on project/core/urls.py
```suggestion
from core.router import CiviWikiRouter
```
You should not delete this line.

2021-09-28 17:32 UTC, gorkemarslan commented
@AbhijithGanesh, could you execute `python manage.py makemigrations` and `python manage.py test` before commiting. Thus, you can be sure that there is no more import error. `makemigrations` is super powerful to debug your code. 🤓

2021-09-28 17:35 UTC, gorkemarslan commented
Your code fails because:
`django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0003_account dependencies reference nonexistent parent node ('api', '0040_delete_invitation')`

Could you consider this? I think the problem is solved after making migrations.

> @AbhijithGanesh, could you execute `python manage.py makemigrations` and `python manage.py test` before commiting. Thus, you can be sure that there is no more import error. `makemigrations` is super powerful to debug your code. 🤓

2021-09-28 18:24 UTC, AbhijithGanesh commented
Is it possible that I clear account migrations because it has a lot of references to api

2021-09-28 18:24 UTC, AbhijithGanesh commented
@gorkemarslan 
 I wanted to remove the pre-existing migrations because they have references to api. Would that be fine?

2021-09-28 18:40 UTC, gorkemarslan commented
I think we shouldn't delete old migrations. Migrations also store historical records of what you've applied on your DB for whole the time. Before production, that can be discussed again but we all should be suspicious to take an action. So, except for squashing and making migrations, we shouldn't do anything about migrations.

Notice that `api` app is not imported migrations. So deleting `api` app won't damage our project.

For [reference](https://stackoverflow.com/questions/28404461/can-i-delete-the-django-migration-files-inside-migrations-directory).

2021-09-29 02:36 UTC, AbhijithGanesh commented
> 
> 
> I think we shouldn't delete old migrations. Migrations also store historical records of what you've applied on your DB for whole the time. Before production, that can be discussed again but we all should be suspicious to take an action. So, except for squashing and making migrations, we shouldn't do anything about migrations. For [reference](https://stackoverflow.com/questions/28404461/can-i-delete-the-django-migration-files-inside-migrations-directory).
> 
> Notice that `api` app is not imported migrations. So deleting `api` app won't damage our project.

Sure, I am working on the migrations keeping in mind all the points
but I'd like to politely remind everyone about the migration tree I had mentioned in one of the earlier issues #1017

2021-09-29 03:54 UTC, AbhijithGanesh commented
@gorkemarslan and @brylie I fixed the migrations too, now can I fix the PEP 8 before we merge it

2021-09-29 15:24 UTC, gorkemarslan commented
Tests are successful and you've already spent too much effort. I think we should approve that PR. After merging, it would be easier to detect what can be done. Then, one can create a new PR to fix them. 
I try to follow but I've lost in changes. 🤕

2021-09-29 15:36 UTC, AbhijithGanesh commented
> 
> 
> Tests are successful and you've already spent too much effort. I think we should approve that PR. After merging, it would be easier to detect what can be done. Then, one can create a new PR to fix them. I try to follow but I've lost in changes. 🤕

I think we're waiting for Hacktober fest to open up

2021-09-30 10:37 UTC, brylie requested changes
Edit: removing the comment as I was mistaken.

2021-09-30 10:46 UTC, brylie commented on project/core/urls.py
> +from threads import urls as api
This should be `threads_urls` now instead of `api`
```suggestion
from threads import urls as threads_urls
```

2021-09-30 10:55 UTC, brylie requested changes
The code, as it stands, fails to load after running `python manage.py collectstatic` with the following error:

> Exception Value: Missing staticfiles manifest entry for dependencies/materialize.min.css'

Please restore the `materialize.min.css` and `materialize.min.js` files and remove those as part of a separate pull request. Otherwise, we need to complete the remaining parts of #1051 in this pull request.

2021-09-30 10:56 UTC, brylie requested changes

2021-09-30 10:56 UTC, brylie commented on project/threads/templates/static/dependencies/materialize.min.css
> -/*!
Let's restore this dependency and remove it in a separate pull request.

2021-09-30 10:56 UTC, brylie commented on project/threads/templates/static/dependencies/materialize.min.js
> -/*!
Let's restore this dependency and remove it in a separate pull request.

2021-09-30 11:41 UTC, brylie requested changes
Overall, this looks great! As mentioned previously, please restore the Materialize CSS and JS files. We can remove those in a separate pull request so that this pull request can be merged.

We will merge this pull request after the files are restored and Hactoberfest begins. Thanks for your excellent work and patience on this task @AbhijithGanesh 😃

2021-09-30 12:37 UTC, AbhijithGanesh commented
> Overall, this looks great! As mentioned previously, please restore the Materialize CSS and JS files. We can remove those in a separate pull request so that this pull request can be merged.
> 
> We will merge this pull request after the files are restored and Hactoberfest begins. Thanks for your excellent work and patience on this task @AbhijithGanesh 😃 

If I work on materialize css and create another PR , unmerged changes including this shall reflect creating unnecessary confusion. Would the be okay

2021-10-01 05:44 UTC, brylie commented
> If I work on materialize CSS and create another PR, unmerged changes including this shall reflect creating unnecessary confusion. 

When creating a new branch, always start your branch from the `develop` branch. Then, make specific changes related to the relevant issue. In this manner, your pull request will contain only appropriate changes (and not unmerged changes from other branches.)

2021-10-01 05:51 UTC, AbhijithGanesh commented
I understand brylie and I'll keep this in my mind

2021-10-01 05:51 UTC, AbhijithGanesh commented
> > If I work on materialize CSS and create another PR, unmerged changes including this shall reflect creating unnecessary confusion. 
> 
> When creating a new branch, always start your branch from the `develop` branch. Then, make specific changes related to the relevant issue. In this manner, your pull request will contain only appropriate changes (and not unmerged changes from other branches.)

Can you please merge the PR since Hacktober has officially begun

2021-10-01 06:55 UTC, brylie commented
@AbhijithGanesh, we couldn't merge the pull request without restoring the Materialize files since the project would not run correctly without them. So I have fixed the Materialize files and will now merge this pull request.

2021-10-01 06:56 UTC, brylie approved these changes
Looks good. Remember to pay close attention when changes are requested.

I have restored the Materialize files so that this project will run.

2021-10-01 06:56 UTC, merged