Restructure project (Close #1052)
CiviWiki/OpenCiviWiki pull request #1059
Opened 2021-09-29 15:16 UTC by gorkemarslan

Closes #1052 

I moved static files to `core` app and try to apply the required refactoring.

2021-09-30 09:24 UTC, gorkemarslan commented
@brylie, is it possible to approve this PR tomorrow?

2021-09-30 11:59 UTC, gorkemarslan commented
@brylie, should I keep the Materialize CSS and JS files in my PR? With this PR, they go into `dependencies` directory in `core` app now. I am asking this because this is the part of Issue #1051.

I think I should remove the Materialize CSS and JS files from `core` app and restore them into `threads` app because I've already deleted them from `threads` app with this PR.

2021-10-01 05:55 UTC, brylie commented
@gorkemarslan go ahead and include the necessary changes from #1051 as part of this pull request. As you know, we will need to run `collectstatic` to make sure we have replaced the relevant static imports with CDN imports. If possible, we should have only one global location for the Materialize (CSS and JS) CDN imports.

2021-10-01 05:55 UTC, brylie commented
Converting to draft since this is still WIP.

2021-10-01 05:59 UTC, gorkemarslan commented
> @gorkemarslan go ahead and include the necessary changes from #1051 as part of this pull request.

Thanks for the clarification.

> Converting to draft since this is still WIP.

Actually, this is what I was going to offer.  👍

2021-10-01 06:00 UTC, brylie requested changes

2021-10-01 06:00 UTC, brylie commented on project/core/settings.py
> +            os.path.join(BASE_DIR, "accounts/templates/accounts"),
These should no longer be necessary, since we have `APP_DIRS: True`, and Django will look within app `templates` directories.

Convention over configuration.


```suggestion
```

2021-10-01 06:11 UTC, gorkemarslan commented
@brylie, I have a question. I have never experienced it. Since I need to wait for being solved #1051 and I've already made changes that are going to conflict with a solution of #1051 (due to the change in Materialize CSS and JS in my branch), what should I do in my branch after being approved the solution of #1051? Will `git fetch` be enough?

2021-10-01 07:36 UTC, brylie commented
In this case, it might be better to try `rebase`. E.g.

1. `git checkout develop`
2. [sync the `develop` branch in your fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-from-the-command-line)
3. `git checkout restructure-project`
4. `git rebase --interactive develop` (see [About Git rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase) for more details)

2021-10-02 07:28 UTC, AbhijithGanesh commented
Can I review the changes? Its being held on draft for a while and it might be better if we move this!

2021-10-02 07:43 UTC, brylie commented
@AbhijithGanesh I've added you as a reviewer for this pull request. Please use the "Review changes" button (pictured below) on the "Files changed" tab to add your review comments.

![image](https://user-images.githubusercontent.com/17307/135708134-fc9dd5df-3e67-4367-afde-bb394af85fe5.png)

2021-10-02 07:43 UTC, AbhijithGanesh commented
> @AbhijithGanesh I've added you as a reviewer for this pull request. Please use the "Review changes" button (pictured below) on the "Files changed" tab to add your review comments.
> 
> ![image](https://user-images.githubusercontent.com/17307/135708134-fc9dd5df-3e67-4367-afde-bb394af85fe5.png)
> 

Will definitely do that! Thank you😃

2021-10-02 07:47 UTC, gorkemarslan commented
@brylie and @AbhijithGanesh, since I created this PR before Oct 1, this PR does not count for the event. I am thinking creating a new one. Is that OK?

2021-10-02 07:48 UTC, brylie commented
> I am thinking creating a new one. Is that OK?

Yes. That would make it easier to ensure there are no conflicts with recent changes.

2021-10-02 07:49 UTC, AbhijithGanesh commented
> @brylie and @AbhijithGanesh, since I created this PR before Oct 1, this PR does not count for the event. I am thinking creating a new one. Is that OK?

Honestly speaking I would've asked you to open a new PR to include this in Hacktober fest, I already missed out one and don't want you or anyone else to miss out again😃.

2021-10-02 15:07 UTC, closed without merging