Add fixtures description to the development guide #1081
CiviWiki/OpenCiviWiki pull request #1084
Opened 2021-10-02 15:28 UTC by LightFelicis

2021-10-02 15:39 UTC, AbhijithGanesh requested changes
Please reference django docs too, that will make this complete.

2021-10-03 10:23 UTC, AbhijithGanesh approved these changes

2021-10-03 14:50 UTC, LightFelicis commented
@AbhijithGanesh do you have merging rights? :-)

2021-10-03 14:52 UTC, AbhijithGanesh commented
> 
> 
> @AbhijithGanesh do you have merging rights? :-)

Only @brylie  does, soon @gorkemarslan will get it.

2021-10-04 05:57 UTC, gorkemarslan requested changes

2021-10-04 05:57 UTC, gorkemarslan commented on CONTRIBUTING.md
> +python manage.py loaddata ./data/categories.json
To show an example from the `sample_threads.json` [file](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/data/sample_threads.json), which will be updated soon:
```json
    {
        "model": "api.thread",
        "fields": {
            "title": "Liquid Fluoride Thorium Reactors",
            "summary": "...",
            "category_id": "2",
            "author_id": "2",
            "created": "2016-10-09 21:07:16.848433+00"
        }
    },
```
Notice that in order to load thread data, we use `category_id` field, so it is expected to be loaded `category` data already. Could you write the line to load `category` data just above the line for `thread` data?

2021-10-04 06:06 UTC, gorkemarslan commented
@LightFelicis, after issue #1079 is fixed, we'll be ready to approve your changes. It is good to see that the guide you prepared really works for the project. If not, we should make changes in the project. Then, we might want you to add a couple of lines here.

We're grateful for your contributions. :blush:

2021-10-04 06:07 UTC, AbhijithGanesh commented
Yes totally, Either you can send in your changes and we can approve it for merging

2021-10-04 06:48 UTC, brylie commented
@LightFelicis, thank you for your contribution :smiley: 

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

2021-10-08 16:08 UTC, gorkemarslan commented
@LightFelicis, could you look at [the requested change](https://github.com/CiviWiki/OpenCiviWiki/pull/1084#discussion_r721061520)?

2021-10-12 05:54 UTC, gorkemarslan commented
@LightFelicis, there is a misunderstanding here. I don't want you to add example fixtures. I just want to explain the change I requested clearly. :smile:  So remove the example.

2021-10-12 05:56 UTC, gorkemarslan requested changes

2021-10-12 05:56 UTC, gorkemarslan commented on CONTRIBUTING.md
> +
You can remove them as I explained.

2021-10-12 07:33 UTC, brylie requested changes

2021-10-12 07:33 UTC, brylie commented on CONTRIBUTING.md
> +```
```suggestion
  Example of values:

```json
```
```

2021-10-12 07:33 UTC, brylie commented on CONTRIBUTING.md
> +
Remove this code as follows:

```suggestion
```

2021-10-14 05:29 UTC, gorkemarslan commented
@LightFelicis, do you need any further clarification or help for the requested changes?

2021-10-16 11:24 UTC, AbhijithGanesh commented
@brylie can you please check this?

2021-10-16 11:25 UTC, AbhijithGanesh commented
I think this PR should be merged once Linting is taken care of, otherwise it won't pass tests

2021-10-16 11:33 UTC, gorkemarslan approved these changes

2021-10-17 08:00 UTC, merged

2021-10-17 08:00 UTC, brylie commented
@all-contributors please add @LightFelicis for docs