Wassaf/ 1033 add formatting to ci
CiviWiki/OpenCiviWiki pull request #1098
Opened 2021-10-04 19:37 UTC by wassafshahzad

Closes 1033

2021-10-05 05:03 UTC, AbhijithGanesh requested changes
Remove .py changes please, please rebranch

2021-10-05 08:30 UTC, brylie requested changes
As @AbhijithGanesh points out, this pull request should only include changes to `.github/workflows/main.yml`

Please modify this branch or start a new one so that only `main.yml` is changed.

2021-10-05 08:30 UTC, brylie commented on .github/workflows/main.yml
> +      run: flake8 project/ --exclude "**/migrations/*.py **/tests/*.py **/tests.py **/__init__.py" --max-line-length 120
Add newline
```suggestion
      run: flake8 project/ --exclude "**/migrations/*.py **/tests/*.py **/tests.py **/__init__.py" --max-line-length 120
      
```

2021-10-09 23:06 UTC, wassafshahzad commented
I'm just gonna start a new branch

2021-10-09 23:06 UTC, closed without merging