Create base template and extend it to templates in core/templates folder
CiviWiki/OpenCiviWiki pull request #1099
Opened 2021-10-05 03:52 UTC by earthprelude

- addresses first part of issue #1049 
- added a new file `core/templates/base.html` with boilerplate HTML to serve as the project's base template 
- edited 4 files in `core/templates` (`about.html`, `how_it_works.html`, `support_us.html`, `landing.html`) to be child templates of `base.html` 
- Modified child templates by removing `<doctype html>`, `<html>`, `<head>` and `<body>` markup, and putting remaining content inside the relevant blocks
- removed CiviWiki from the title of child templates when present (in `how_it_works.html` and `landing.html`)

2021-10-05 08:26 UTC, brylie requested changes

2021-10-05 08:26 UTC, brylie commented on project/core/templates/base.html
> +    {% block content %}{% endblock content %}
Let's include the static navigation and footer here, and remove them from child templates.
```suggestion
    {% include "static_nav.html" %}
    
    {% block content %}{% endblock content %}
    
    {% include "static_footer.html" %}
```

2021-10-05 08:26 UTC, brylie commented on project/core/templates/about.html
>      {% include "static_footer.html" %}
Let's move the static navigation and footer to the `base.html`.
```suggestion
    <div id="about"></div>
```

2021-10-05 08:26 UTC, brylie commented on project/core/templates/how_it_works.html
>      {% include "static_footer.html" %}
Let's move the static navigation and footer to the `base.html`.
```suggestion
    <div id="howitworks"></div>
```

2021-10-05 08:26 UTC, brylie commented on project/core/templates/landing.html
>      {% include "static_footer.html" %}
Let's move the static navigation and footer to the `base.html`.
```suggestion
    <div id="landing"></div>
```

2021-10-05 08:26 UTC, brylie commented on project/core/templates/support_us.html
>      {% include "static_footer.html" %}
Let's move the static navigation and footer to the `base.html`.
```suggestion
    <div id="supportus"></div>
```

2021-10-06 09:20 UTC, brylie requested changes

2021-10-06 09:20 UTC, brylie commented on project/core/templates/base.html
> +<!DOCTYPE HTML>
This should remain `<!DOCTYPE html>`: https://developer.mozilla.org/en-US/docs/Glossary/Doctype
```suggestion
<!DOCTYPE html>
```

2021-10-07 06:44 UTC, brylie approved these changes
Looks good to me.

@gorkemarslan, any thoughts?

2021-10-07 07:29 UTC, gorkemarslan approved these changes

2021-10-07 07:36 UTC, gorkemarslan commented
@brylie, the templates seem good, we can approve this PR.

@earthprelude, thank you for your effort. The finished work looks amazing.

2021-10-07 08:52 UTC, merged

2021-10-07 08:53 UTC, brylie commented
@all-contributors please add @earthprelude for code

2021-10-07 22:57 UTC, earthprelude commented
Thank you! And thanks @brylie for all your help.