Front end fixes
CiviWiki/OpenCiviWiki pull request #1114
Opened 2021-10-07 16:20 UTC by AbhijithGanesh

Addresses of #1090

2021-10-07 16:20 UTC, pep8speaks commented
Hello @AbhijithGanesh! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`project/threads/urls.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/ff7c81e8f0ec4260277129a6f85e0b0c09c5eb07/project/threads/urls.py):

> [Line 10:65](https://github.com/CiviWiki/OpenCiviWiki/blob/ff7c81e8f0ec4260277129a6f85e0b0c09c5eb07/project/threads/urls.py#L10): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-10-07 16:35 UTC, gorkemarslan requested changes
Please remove  "frontend_views" from `INSTALLED_APPS`. This is why tests fail.

2021-10-07 16:38 UTC, AbhijithGanesh commented
> 
> 
> Please remove "frontend_views" from `INSTALLED_APPS`. This is why tests fail.

I resolved it.

2021-10-07 16:48 UTC, gorkemarslan requested changes

2021-10-07 16:48 UTC, gorkemarslan commented on project/accounts/urls/urls.py
> +    path("profile/<str:username>/", user_profile, name="profile"),
Solve duplication of lines

2021-10-07 16:48 UTC, gorkemarslan commented on project/threads/urls.py
> +    path("thread/<int:thread_id>/", issue_thread, name="issue thread"),
In `core/urls.py`, we are using:

`path("api/", include(threads)),`

to get `threads` app urls.

But you're using `api/thread/<int:thread_id>/` for `issue_thread` and `api/` for `base`. So fix it to remove `api/` suffix from the new views you added.

2021-10-07 17:00 UTC, gorkemarslan requested changes

2021-10-07 17:00 UTC, gorkemarslan commented on project/accounts/urls/urls.py
> +    path("", base_view),
`base_view` should not be in `accounts` app. You also added it to `threads` app

2021-10-07 17:00 UTC, gorkemarslan commented on project/core/views/views.py
> +from core.custom_decorators import full_profile, login_required
To keep the `core` app simple, could you place them to the `threads` app and `core/views/views.py. `For example, after login, a user is welcomed by landing view that includes threads.

2021-10-07 17:01 UTC, AbhijithGanesh commented on project/accounts/urls/urls.py
> +    path("", base_view),
Yeah but the empty url is mounted on accounts

2021-10-07 17:02 UTC, AbhijithGanesh commented on project/core/views/views.py
> +from core.custom_decorators import full_profile, login_required
sure, Will make changes.

2021-10-07 17:04 UTC, gorkemarslan commented on project/accounts/urls/urls.py
> +    path("", base_view),
But they are irrelevant to `accounts` app. You can add all of them to the `threads` app and get them from core app by directly calling the related views there.

2021-10-07 17:14 UTC, AbhijithGanesh commented
@brylie and @gorkemarslan I didn't touch the database side of things yet it is failing I don't know why!

2021-10-07 17:17 UTC, gorkemarslan commented
@AbhijithGanesh, could you check the requested changes?

2021-10-07 17:19 UTC, gorkemarslan requested changes

2021-10-07 17:19 UTC, gorkemarslan commented on project/core/settings.py
> +DEBUG = os.getenv("DEBUG", True)
You are not supposed to make a change for this section. Please revert it.

2021-10-07 17:24 UTC, AbhijithGanesh commented on project/core/settings.py
> +DEBUG = os.getenv("DEBUG", True)
Oh sorry that this change popped up. Will resolve immediately

2021-10-07 17:25 UTC, AbhijithGanesh commented on project/accounts/urls/urls.py
> +    path("", base_view),
I have made those changes

2021-10-07 17:27 UTC, AbhijithGanesh commented on project/core/settings.py
> +DEBUG = os.getenv("DEBUG", True)
@gorkemarslan still the tests fail

2021-10-07 17:40 UTC, AbhijithGanesh commented
@gorkemarslan and @brylie there is one test case specifically related to user creation, that stems from a different branch since I haven't touched any of the DB files.

2021-10-07 17:48 UTC, AbhijithGanesh commented
```py
     def test_register_view_redirects_on_success(self):
        """Whether register view redirects to the base view after the successive try"""
    
        response = self.client.post(reverse('accounts_register'),
                                    {'username': "newuser",
                                     "email": "newuser@email.com",
                                     'password': "password123"})
       self.assertRedirects(response, expected_url=reverse('base'), status_code=302, target_status_code=200)

```
Is this test correct? I wonder how a registered and logged in user reverse back into base.html

2021-10-07 19:56 UTC, gorkemarslan commented
@AbhijithGanesh, yes the test is correct. I requested a change to handle the test fail but I guess you missed it. Could you look at [it](https://github.com/CiviWiki/OpenCiviWiki/pull/1114#discussion_r724359388)?

2021-10-08 03:34 UTC, AbhijithGanesh commented
@gorkemarslan and @brylie all tests passed please review

2021-10-08 05:34 UTC, gorkemarslan requested changes

2021-10-08 05:34 UTC, gorkemarslan commented on project/core/urls.py
> +    path("", include(threads)),
Now, we're losing the `api/` suffix for api-related urls of `threads` app. In [accounts](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/accounts) app we had the same problem. We didn't want webpages urls to have `api/` suffix that comes from `core/urls.py`. To solve it we created [urls](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/accounts/urls) folder and created two files inside: `api.py` to put api-related urls and `urls.py` to put webpages urls.

So we can do the same here.

Create urls folder in `threads` app:

```
urls
  |_ api.py
  |_ urls.py
```

Move all codes written in `urls.py` to `api.py`:
https://github.com/CiviWiki/OpenCiviWiki/blob/2b910c626c62c5d07bc455a18274c1ac8649c5f6/project/threads/urls.py#L1-L42

Update the related part in core/urls.py:
https://github.com/CiviWiki/OpenCiviWiki/blob/2b910c626c62c5d07bc455a18274c1ac8649c5f6/project/core/urls.py#L32

to be
```python
    path("api/", include(threads.urls.api)),
```

Now, all api-related urls in `threads` app are located in `threads/urls/api.py` and have `api/` suffix.

The views came from `frontend_view` folder are moved to `threads/views.py`. Let't put the all relevant urls into `threads/url/urls.py`.

```python
urlpatterns = [
    path("about/", views.about_view, name="about"),
    path("support_us/", support_us_view, name="support us"),
    path("howitworks/", how_it_works_view, name="how it works"),
    path("thread/<int:thread_id>/", issue_thread, name="issue thread"),
    path("thread/<int:thread_id>/csv/", civi2csv, name="civi2csv"),
    path("", base_view, name="base"),
]
```

Of course, update core/urls.py:

```python
    path("", include(threads.urls.urls)),
```

So finally, the core/urls.py should be such that:

```python
    path("api/", include(threads.urls.api)),
    path("", include(threads.urls.urls)),
```

2021-10-08 06:26 UTC, AbhijithGanesh commented on project/core/urls.py
> +    path("", include(threads)),
Can you please check it now? I have made those changes.

2021-10-08 12:19 UTC, gorkemarslan commented
@AbhijithGanesh, could  you look at my last [requested change](https://github.com/CiviWiki/OpenCiviWiki/pull/1114#discussion_r724712280)? You are supposed to create the `urls` folder in `threads` app to move `urls` files to it. I audited your repo and I didn't see such a structure.

Do you need more clarification? How can I help you, if you're not sure what to do?

2021-10-08 12:20 UTC, AbhijithGanesh commented
I will see the requested changes, I am really sorry for the last test failing, I should have paid more attention with the URLs, sorry @gorkemarslan

2021-10-08 12:23 UTC, gorkemarslan requested changes

2021-10-08 12:23 UTC, gorkemarslan commented on project/threads/views/views.py
> +import json
You shouldn't create a new folder for `views`. Could you revert this step so that the previous `threads` views and all `frontend_views/views.py` to be in `threads/views.py`?

2021-10-08 12:29 UTC, gorkemarslan commented
@AbhijithGanesh, as I said before all mistakes are welcomed. :smile: Please just try to understand our purpose here. The most important thing is to understand the logic of these tasks. That's all. We all help each other without any limitation.

Go out for fresh air before starting, it will make you fell great. :+1: 
Then look at again the last requested changes, if they are not clear to you, I'll explain more. If you want, I can add them to the relevant issue as sub-tasks.

2021-10-11 08:19 UTC, AbhijithGanesh commented
I can't locally resolve conflicts @gorkemarslan and @brylie

2021-10-11 08:23 UTC, AbhijithGanesh commented
Did someone disable workflows?

2021-10-11 09:22 UTC, AbhijithGanesh commented
I don't have the frontend_views in my branch, I think it is the develop branch which has the directory of frontend_views

2021-10-11 09:46 UTC, brylie commented
I think some changes were made to the `frontend_views` folder that got merged into `develop`. This would make your branch slightly out-of-sync with `develop` since you branched at a different point that didn't have the newer changes. Basically, you have to merge the recent changes into your work manually, by reviewing the code currently in `develop` and copying those changes into the new location in your branch.

2021-10-11 09:47 UTC, AbhijithGanesh commented
Can I close this PR and reopen?🤣😅

2021-10-11 09:48 UTC, brylie commented
Yes, you can start your pull request from the latest develop.

However, it will be useful to learn how to handle conflicts at some point, so you don't need to "restart" your branches whenever conflicts happen.

https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

2021-10-11 09:48 UTC, closed without merging

2021-10-11 09:53 UTC, brylie commented
Make sure also to describe precisely how your pull request completes parts of the related issue. I.e., the description is a bit ambiguous currently.