Routing issues
CiviWiki/OpenCiviWiki pull request #1116
Opened 2021-10-08 08:27 UTC by SimonDamberg

I have fixed the routing issues in the header.

Closes #1115

2021-10-08 08:35 UTC, brylie requested changes
While we are working on this related code, would you mind changing the route names to use snake case?

E.g. in the related `urls.py` the route name would be `how_it_works`, `issue_thread`, and `support_us`.

https://github.com/CiviWiki/OpenCiviWiki/blob/3c3282cd091246b041adc6c71099a288d4a77693/project/frontend_views/urls.py#L6-L9

That way, our route names will be consistent.

2021-10-08 08:39 UTC, brylie requested changes

2021-10-08 08:39 UTC, brylie commented on project/core/templates/static_nav.html
> +            <li><a class="dark-white-text menu-text" href="{% url 'support us' %}">{% trans "Support Us" %}</a></li>
Let's change these to camel case here and update the related `urls.py` file.
```suggestion
            <li><a class="dark-white-text menu-text" href="{% url 'how_it_works' %}">{% trans "How CiviWiki Works" %}</a></li>
            <li><a class="dark-white-text menu-text" href="{% url 'about' %}">{% trans "About Us" %}</a></li>
            <li><a class="dark-white-text menu-text" href="{% url 'support_us' %}">{% trans "Support Us" %}</a></li>
```

https://github.com/CiviWiki/OpenCiviWiki/blob/3c3282cd091246b041adc6c71099a288d4a77693/project/frontend_views/urls.py#L6-L9

2021-10-08 08:39 UTC, brylie commented on project/core/templates/static_nav.html
> +            <li><a class="dark-white-text menu-text" href="{% url 'support us' %}">{% trans "Support Us" %}</a></li>
Let's use snake_case here and be sure to update the related `urls.py`
```suggestion
            <li><a href="{% url 'accounts_login' %}">LOGIN / SIGN UP</a></li>
            <li><a class="dark-white-text menu-text" href="/">main</a></li>
            <li><a class="dark-white-text menu-text" href="{% url 'how_it_works' %}">{% trans "How CiviWiki Works" %} </a></li>
            <li><a class="dark-white-text menu-text" href="{% url 'about' %}">{% trans "About Us" %} </a></li>
            <li><a class="dark-white-text menu-text" href="{% url 'support_us' %}">{% trans "Support Us" %}</a></li>
```

https://github.com/CiviWiki/OpenCiviWiki/blob/3c3282cd091246b041adc6c71099a288d4a77693/project/frontend_views/urls.py#L6-L9

2021-10-08 08:46 UTC, SimonDamberg commented on project/core/templates/static_nav.html
> +            <li><a class="dark-white-text menu-text" href="{% url 'support us' %}">{% trans "Support Us" %}</a></li>
I agree! I have updated the PR.

2021-10-08 08:48 UTC, SimonDamberg commented
@brylie I have updated the PR according to your requested changes 😄

2021-10-08 15:59 UTC, gorkemarslan requested changes

2021-10-08 15:59 UTC, gorkemarslan commented on project/core/templates/static_nav.html
> +            <li><a class="dark-white-text menu-text" href="/">main</a></li>
We have base_view for the main page (`"/"`):

https://github.com/CiviWiki/OpenCiviWiki/blob/3c3282cd091246b041adc6c71099a288d4a77693/project/frontend_views/urls.py#L11

Could you use the route name of this view such that:

`<li><a class="dark-white-text menu-text" href="{% url 'base' %}">main</a></li>`

2021-10-08 16:03 UTC, SimonDamberg commented on project/core/templates/static_nav.html
> +            <li><a class="dark-white-text menu-text" href="/">main</a></li>
Fixed this 👍🏼

2021-10-08 16:05 UTC, gorkemarslan approved these changes

2021-10-11 08:14 UTC, brylie approved these changes

2021-10-11 08:14 UTC, merged

2021-10-11 08:14 UTC, brylie commented
@all-contributors please add @SimonDamberg for code