Edit other templates to extend base.html
CiviWiki/OpenCiviWiki pull request #1117
Opened 2021-10-09 02:59 UTC by earthprelude

- closes #1049 
- edited the 12 remaining templates listed to make them extend `core/templates/base.html`
- modified files by removing `<doctype html>`, `<html>`, `<head>` and `<body>` markup, and adding relevant template tags
- removed CiviWiki from the title of child templates when present 
- deleted the file `threads/templates/threads/base/links.html` and removed references to it 
-----------------------
- editing `entry_base.html` to extend `base.html` created 2 levels of template inheritance, because `entry_base.html` is itself the parent template of 6 other templates. To prevent the error caused by `entry_base.html` having 2 blocks with the same name (`content`), I changed the name of the empty block it defines from `content` to `entry_content`, and updated its 6 child templates to match
- removed `{% include "static_nav.html" %}` from `base.html` because several child templates include a different navigation bar (`global_nav.html`)
- returned `{% include "static_nav.html" %}` to the 4 child templates in the `core/templates` folder

2021-10-11 08:28 UTC, brylie requested changes
This looks great so far! Let's just revert the `entry_content` block to be `content`. All we have to do is remove the outer `block content` wrapper from the `entry_base.html` so there is only the remaining `block content` within the `div`s.

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/register/entry_base.html
> +{% endblock content %}
We don't need to wrap all of the `div`s with `block content`. Rather, we can just have a single `block content`within the divs, as was previously the case.

```html
<div class="entry-base center-align valign-wrapper">
    <div class="entry-forms">
        <div class="card wrapper z-depth-3">
                <div class="card-content" id="entry-content">
                    {% block content %}{% endblock %}
                </div>
            </div>
            <div class="back-to-main">
                <a class="text" href="/"><i class="material-icons mini">keyboard_backspace</i>{% trans "Back to Main" %}</a>
            </div>
    </div>
</div>
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/register/entry_base.html
> +{% block content %}
Remove this block wrapper
```suggestion
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/register/entry_base.html
> +{% endblock content %}
Remove this block wrapper
```suggestion
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/register/entry_base.html
> +                    {% block entry_content %}{% endblock %}
This should remain as `block content`
```suggestion
                    {% block content %}{% endblock %}
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/register/register.html
> +{% block entry_content %}
This should remain as `content`
```suggestion
{% block content %}
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/users/password_reset_complete.html
> +{% block entry_content %}
This should remain as `content`
```suggestion
{% block content %}
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/users/password_reset_confirm.html
> +{% block entry_content %}
This should remain as `content`
```suggestion
{% block content %}
```

2021-10-11 08:28 UTC, brylie commented on project/accounts/templates/accounts/users/password_reset_done.html
> +{% block entry_content %}
This should remain as `content`
```suggestion
{% block content %}
```

2021-10-11 22:42 UTC, earthprelude commented
Hi @brylie, thanks! 

When I tried making these suggested changes, it caused the following change to the login screen: 
![image](https://user-images.githubusercontent.com/75330343/136856671-59bb185a-bca1-4575-8b98-5df563a86535.png)
The same thing happens to the register screen:
![image](https://user-images.githubusercontent.com/75330343/136859376-5de2cf5f-c947-458d-980f-ac0cea276dcb.png)

It looks like the child templates of `entry_base.html` are no longer rendering properly (including `login.html` and `register.html`). The `<div>` content of `entry_base.html`, that used to be shared with all its child templates, doesn't seem to show up anymore.  

I think this problem was caused by removing the outer `block content` wrapper from `entry_base.html`. Since the `<div>` content is no longer enclosed in `{% block content %}...{% endblock %}`, it doesn't fill in the empty `{% block content %}{endblock}` of `base.html`, and doesn't get rendered on the screen. 

Since `entry_base.html` is serving 2 roles (as both child template of `base.html`, and parent template of 6 other files), I think it needs 2 separate sets of blocks to perform those 2 different roles (both child and parent). If we remove one set, the 2 levels of template inheritance don't work correctly. 

If I revert the changes and leave the files how they were (with separate `content` and `entry_content` blocks), the child templates render normally, and I can see the regular login screen again: 
![image](https://user-images.githubusercontent.com/75330343/136857774-f5919aa2-a7a2-4cb7-b2af-e27b766d63da.png)

2021-10-12 07:25 UTC, brylie commented
OK, my bad. We'll merge your changes as they are. Thanks!

2021-10-12 07:26 UTC, brylie approved these changes

2021-10-12 07:26 UTC, merged