Resolving frontend views
CiviWiki/OpenCiviWiki pull request #1122
Opened 2021-10-11 10:19 UTC by AbhijithGanesh

Closes issue #1090

This issue resolves the following:
- Removed files related to frontend_views and the directory itself
- Fixed improper naming and gives actual literal names
- Moves [ https://github.com/CiviWiki/OpenCiviWiki/blob/d7f24fad7c0a2565da3bf2cd54e89a847d7479dd/project/frontend_views/views.py ](user_profile) and related urls
- Moves frontend views to threads

2021-10-11 10:20 UTC, AbhijithGanesh commented
@brylie New PR, same issues

2021-10-11 15:56 UTC, brylie commented
Would you please add to your pull request description a bit more information about the parts of #1090 that this pull request resolves?

2021-10-11 15:58 UTC, brylie commented
If possible, split issue #1090 into multiple issues so this pull request can close one of the issues.

2021-10-11 16:08 UTC, AbhijithGanesh commented
If you merge this, it should be good I guess

2021-10-11 17:05 UTC, AbhijithGanesh commented
@brylie I have updated the description and this branch can be merged

2021-10-11 18:47 UTC, gorkemarslan requested changes

2021-10-11 18:47 UTC, gorkemarslan commented on project/accounts/urls/urls.py
> +    path("", base_view),
`base_view` should not be in `accounts` app. You add it to `threads` app, as well. Please remove this and the related import.

2021-10-11 18:47 UTC, gorkemarslan commented on project/core/urls.py
> +    path("", base_view),
Remove it because you use it in `threads.urls.urls` in this branch.

2021-10-11 18:47 UTC, gorkemarslan commented on project/core/urls.py
> +    path("howitworks/", how_it_works_view, name="how it works"),
Remove them, they are in `threads.urls.urls `in your branch.

2021-10-11 18:47 UTC, gorkemarslan commented on project/threads/urls/urls.py
> +    path("create-group", create_group, name="create group"),
Could you add ending slash `'/'` to them?

2021-10-11 18:47 UTC, gorkemarslan commented on project/threads/views/views.py
> +        return Response(serializer.data)
`CategoryViewSet` somehow appears in the `threads` app but it is also present in the `category` app. Could you remove this one and fix the import?

2021-10-11 19:03 UTC, pep8speaks commented
Hello @AbhijithGanesh! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

















* In the file [`project/threads/views/views.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/d615e64e58107e16e0e02a2c6499e017c121df93/project/threads/views/views.py):

> [Line 123:1](https://github.com/CiviWiki/OpenCiviWiki/blob/d615e64e58107e16e0e02a2c6499e017c121df93/project/threads/views/views.py#L123): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace



##### Comment last updated at 2021-10-12 10:32:15 UTC

2021-10-11 19:07 UTC, AbhijithGanesh commented
@gorkemarslan finished those changes

2021-10-12 05:26 UTC, gorkemarslan requested changes

2021-10-12 05:26 UTC, gorkemarslan commented on project/accounts/urls/urls.py
> +from threads.views.views import base_view
You can remove this unused import.

2021-10-12 05:28 UTC, gorkemarslan requested changes

2021-10-12 05:28 UTC, gorkemarslan commented on project/core/urls.py
> +from threads.views.views import about_view, support_us_view, how_it_works_view, base_view
You can remove these two lines including `from threads import urls as threads`.

2021-10-12 05:29 UTC, AbhijithGanesh commented on project/core/urls.py
> +from threads.views.views import about_view, support_us_view, how_it_works_view, base_view
I will remove them

2021-10-12 05:30 UTC, AbhijithGanesh commented on project/core/urls.py
> +from threads.views.views import about_view, support_us_view, how_it_works_view, base_view
Removed

2021-10-12 05:32 UTC, gorkemarslan commented
@AbhijithGanesh, I see that you changed static file imports to be via CDN in the templates. Is there any open issue for that. Or you just want to improve code quality?

2021-10-12 05:34 UTC, AbhijithGanesh commented
There is no open issue for that since it deals with dependency files(which can be directly loaded from CDN)

2021-10-12 05:51 UTC, gorkemarslan commented
It would be better if you specify your purpose on usage of CDN in the PR message.

Except for CDN, the PR is fine to me.

Let's wait for @brylie to decide to keep CDN usage or revert them back.

If @brylie says you are allowed to make these changes in CDN, then you need to remove the related files in the [dependencies](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/core/templates/static/dependencies) folder because no need to use them anymore. In that situation, you also need to edit the the issue #1090 to specify CDN usages in order to track it in the future.

If @brylie says let's handle this situation in another issue, you should revert them.

In either case, before pushing any commits related to CDN, let's wait @brylie. :smile:  

Another point, the number of commits you pushed is a little bit excessive. When you open this PR, you've already added more than 30 commits. That seems scary in the first glance. Next time, could you squash relevant changes to be just one commit instead of many in order to decrease your number of commits? :smile:

2021-10-12 05:52 UTC, AbhijithGanesh commented
I haven't made any changes tbh, I just reverted my commit to make sure we can add it to a different issue

2021-10-12 05:52 UTC, AbhijithGanesh commented
I will reduce the number of commits next time

2021-10-12 06:02 UTC, gorkemarslan approved these changes

2021-10-12 06:03 UTC, AbhijithGanesh commented
Also massive thanks to @gorkemarslan for going through this for the n-th time, I have virtually lost count, thank you for this wonderful work

2021-10-12 07:34 UTC, brylie commented
> Let's wait for @brylie to decide to keep CDN usage or revert them back.
>
> If @brylie says you are allowed to make these changes in CDN, then you need to remove the related files in the dependencies folder because no need to use them anymore. In that situation, you also need to edit the the issue #1090 to specify CDN usages in order to track it in the future.

We can keep the CDN links and remove the related files, as @gorkemarslan mentioned.

2021-10-12 07:34 UTC, brylie requested changes
Please resolve conflicts.

2021-10-12 10:39 UTC, brylie approved these changes

2021-10-12 10:40 UTC, AbhijithGanesh commented
Can you merge this soon brylie?

2021-10-12 10:40 UTC, brylie commented
I approved these changes and will merge the pull request once the pull request is linked to the related GitHub issue via a supported keyword.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

2021-10-12 10:43 UTC, brylie commented
Note that GitHub is a bit picky with the supported keywords, so you need to follow the syntax exactly as described in the official documentation

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2021-10-12 10:44 UTC, brylie commented
When the syntax is correct, the linked issue will appear in the pull request sidebar section depicted below:

![image](https://user-images.githubusercontent.com/17307/136941570-32560da4-b7c6-417e-8f2c-d6e38f2c96a5.png)

2021-10-12 10:45 UTC, brylie commented
The current comment is close, but not close enough for GitHub to recognize the link

![image](https://user-images.githubusercontent.com/17307/136941708-0316c022-d115-4421-838a-2e96bd4e60da.png)

2021-10-12 10:48 UTC, brylie commented
@AbhijithGanesh, notice how the comment in pull request #1124 is automatically linked to issue #1101

![image](https://user-images.githubusercontent.com/17307/136942035-04e9c634-630d-468c-9a84-09b79070584a.png)

2021-10-12 10:49 UTC, AbhijithGanesh commented
Closes #1090

2021-10-12 10:51 UTC, AbhijithGanesh commented
Now it shows

2021-10-12 10:55 UTC, merged