Removed states-related code from API views
CiviWiki/OpenCiviWiki pull request #1128
Opened 2021-10-12 08:15 UTC by sg-007

Removed level, state and location variables and US_STATES constant
closes #1106

## Specific code to remove

- [x] Remove `level_CHOICES`, `level`, and `state`: https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/threads/models.py#L90-L95

- [x] Remove `US_STATES` imports: 
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/3de9e1eb30765d665770c3d56fbd3c4143d30eb6/project/threads/models.py#L9
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L13
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L23

- [x]  Remove `US_STATES` constant: https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/core/constants.py#L13-L66

- [x]  Remove "state" and "level" code from Thread model manager: https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L47-L49

- [x]  Remove states-related code from API views:
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L46
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L49
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L130
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/b15b942e21531e2252726ee6d0e37425be6977fa/project/frontend_views/views.py#L132-L134
    - [x] Remove `location` variable https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L388-L392
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L402-L404
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L43
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L45-L47
    - [x] Remove only level and state fields https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/api.py#L357

- [x] Remove state and level fields from serializers:
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L111-L112
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L141-L142
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/d507b0d47908d02dc40ceb0110a96d0e0f156d35/project/threads/serializers.py#L180-L181
- [x] create database migrations with `python manage.py makemigrations`

2021-10-12 08:17 UTC, brylie commented
@Saatvat please add a description to this pull request, including a link to the related issue.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

2021-10-12 08:21 UTC, brylie requested changes

2021-10-12 08:21 UTC, brylie commented on project/frontend_views/views.py
> -    states = sorted(US_STATES, key=lambda s: s[1])
Remember to also remove the import from the top of this file.

Also, we can delete the related `US_STATES` constant since it is no longer needed in the project.

2021-10-12 08:21 UTC, brylie commented
Converting to draft since this pull request is still work-in-progress.

2021-10-12 08:27 UTC, sg-007 commented on project/frontend_views/views.py
> -    states = sorted(US_STATES, key=lambda s: s[1])
Ok will do that.
Also how do I add a description to the pull request?
This is my first experience with Github and therefore I'm still learning.

2021-10-12 08:31 UTC, brylie commented on project/frontend_views/views.py
> -    states = sorted(US_STATES, key=lambda s: s[1])
You can click the ellipsis button on the pull request near where it says "No description provided.":

![Peek 2021-10-12 11-30](https://user-images.githubusercontent.com/17307/136920975-dcac46df-7575-465e-880f-285f774e6327.gif)

In the future, please follow the pull-request template, which encourages contributors to add a description and link the pull request to a related issue.

2021-10-12 08:32 UTC, brylie commented on project/frontend_views/views.py
> -    states = sorted(US_STATES, key=lambda s: s[1])
In any case, we are grateful for your contribution to CiviWiki :smiley:

2021-10-12 08:33 UTC, sg-007 commented on project/frontend_views/views.py
> -    states = sorted(US_STATES, key=lambda s: s[1])
Thank You!
Will definitely follow the template for further pull requests.

2021-10-12 10:38 UTC, brylie requested changes
Please restore the `json` import.

2021-10-12 10:38 UTC, brylie commented on project/frontend_views/views.py
> -import json
Removing this import will cause the code to fail.

2021-10-12 10:44 UTC, sg-007 commented on project/frontend_views/views.py
> -import json
Updated...

2021-10-12 10:53 UTC, brylie commented
Converting to draft since the pull request is still work-in-progress.

2021-10-12 10:54 UTC, brylie requested changes

2021-10-12 10:54 UTC, brylie commented on project/frontend_views/views.py
> -from core.constants import US_STATES
Remember to delete the `US_STATES` constant from the `core/constants.py` file.

2021-10-12 10:54 UTC, brylie requested changes
Please make sure to complete all of the steps outlined in issue #1106 

There are only a couple of other changes to make. Great work so far! :smiley:

2021-10-12 11:01 UTC, sg-007 commented
Sure, will get back to you with further changes

2021-10-12 11:15 UTC, pep8speaks commented
Hello @Saatvat! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: 

##### Comment last updated at 2021-10-15 09:19:52 UTC

2021-10-12 11:16 UTC, brylie requested changes
Be sure to resolve any lint messages mentioned by @pep8speaks

2021-10-12 11:19 UTC, Saatvat commented
Resolved

2021-10-12 11:22 UTC, brylie commented
I have added a checklist to this pull request description to make sure we keep track of all related changes. Please check off the changes you have made so far to see how close this issue is to completion.

2021-10-12 11:30 UTC, sg-007 commented
> I have added a checklist to this pull request description to make sure we keep track of all related changes. Please check off the changes you have made so far to see how close this issue is to completion.

Only the last one i.e. "create database migrations with python manage.py makemigrations" is left

2021-10-12 15:32 UTC, sg-007 commented
Why does this branch have conflicts?
And how do I create database migrations?

2021-10-13 08:05 UTC, brylie commented
The branch has conflicts because other changes have been made to the `develop` branch since this branch was created. Git doesn't know how to resolve the changes in a safe way that preserves your work as well as the work in `develop`. Resolving conflicts is a common aspect of software development. Please use the following instructions to resolve conflicts in this branch.

https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

2021-10-13 08:05 UTC, brylie commented
> how do I create database migrations?

Use the command `python manage.py makemigrations`

Here is a bit more info about Django migrations: https://docs.djangoproject.com/en/3.2/topics/migrations/

2021-10-13 11:01 UTC, sg-007 commented
> > how do I create database migrations?
> 
> Use the command `python manage.py makemigrations`
> 
> Here is a bit more info about Django migrations: https://docs.djangoproject.com/en/3.2/topics/migrations/

It's throwing a name error 
![err](https://user-images.githubusercontent.com/55142587/137120657-fcd9d4bf-beb6-4e18-b3a3-a38b352e00c3.jpg)

Line 215 - ![line](https://user-images.githubusercontent.com/55142587/137120688-46b9424e-3c39-4fbb-a261-4cc5a43331df.jpg)

2021-10-13 11:24 UTC, gorkemarslan requested changes

2021-10-13 11:24 UTC, gorkemarslan commented on project/threads/models.py
> -from core.constants import CIVI_TYPES, US_STATES
You should only remove `US_STATES`. Notice that you also deleted` CIVI_TYPES` so the project cannot find `CIVI_TYPES` if you remove it.

Please leave the line as follows:
```python
from core.constants import CIVI_TYPES
```

Then your migration error will disappear. Try to execute `python manage.py makemigrations` again.

2021-10-13 11:29 UTC, brylie commented
I'm converting this pull request to draft status since there is still work in progress.

2021-10-13 14:33 UTC, sg-007 commented on project/threads/models.py
> -from core.constants import CIVI_TYPES, US_STATES
> You should only remove `US_STATES`. Notice that you also deleted` CIVI_TYPES` so the project cannot find `CIVI_TYPES` if you remove it.
> 
> Please leave the line as follows:
> 
> ```python
> from core.constants import CIVI_TYPES
> ```
> 
> Then your migration error will disappear. Try to execute `python manage.py makemigrations` again.

Worked now, thanks👍

2021-10-13 15:30 UTC, brylie requested changes
Please [resolve conflicts](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) in this branch.

2021-10-14 07:53 UTC, Saatvat commented
> Please [resolve conflicts](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) in this branch.

The working tree is clean and doesn't show any conflicts and the sub-folder 'frontend_views' doesn't exist.
How do I resolve this?

2021-10-14 08:02 UTC, brylie commented
GitHub says there are conflicts in the following files:

![image](https://user-images.githubusercontent.com/17307/137275777-318398a8-3576-4df3-88af-d1a9c577f911.png)

For the `project/frontend_views/views.py`, you may need to [resolve a merge conflict caused by competing changes to a file, where a person deleted a file in one branch and another person edits the same file](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#removed-file-merge-conflicts).

The `.all-contributorsrc` file should be done by [resolving a merge conflict caused by competing line changes, you must choose which changes to incorporate from the different branches in a new commit](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts).

2021-10-14 16:36 UTC, sg-007 commented
Conflicts resolved

2021-10-15 09:11 UTC, brylie commented on .all-contributorsrc
> +        "review"
```suggestion
        "review",
        "doc"
```

2021-10-15 09:11 UTC, brylie commented on .all-contributorsrc
> +  "repoHost": "https://github.com"
```suggestion
  "repoHost": "https://github.com",
  "skipCi" true,
  "contributorsSortAlphabetically": true
```

2021-10-15 09:14 UTC, brylie commented on README.md
> +
```suggestion
## Contributors

Thanks to these wonderful people ([emoji key](https://allcontributors.org/docs/en/emoji-key)):

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tr>
    <td align="center"><a href="https://github.com/abhiprojectz"><img src="https://avatars.githubusercontent.com/u/64596494?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Abhi </b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=abhiprojectz" title="Code">💻</a></td>
    <td align="center"><a href="https://abhijithganesh.github.io"><img src="https://avatars.githubusercontent.com/u/67182544?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Abhijith Ganesh</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=AbhijithGanesh" title="Code">💻</a> <a href="#projectManagement-AbhijithGanesh" title="Project Management">📆</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=AbhijithGanesh" title="Documentation">📖</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/issues?q=author%3AAbhijithGanesh" title="Bug reports">🐛</a></td>
    <td align="center"><a href="https://github.com/adityamittl"><img src="https://avatars.githubusercontent.com/u/76921082?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Aditya Mittal</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=adityamittl" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/a7madnassar"><img src="https://avatars.githubusercontent.com/u/2473403?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Ahmed Nassar</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=a7madnassar" title="Code">💻</a> <a href="#infra-a7madnassar" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a></td>
    <td align="center"><a href="https://github.com/alanCalvillo-Wizeline"><img src="https://avatars.githubusercontent.com/u/72406611?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Alan Calvillo</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/pulls?q=is%3Apr+reviewed-by%3AalanCalvillo-Wizeline" title="Reviewed Pull Requests">👀</a></td>
    <td align="center"><a href="https://github.com/alecxvs"><img src="https://avatars2.githubusercontent.com/u/513932?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Alec Sears</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/issues?q=author%3Aalecxvs" title="Bug reports">🐛</a></td>
    <td align="center"><a href="https://github.com/dummy26"><img src="https://avatars.githubusercontent.com/u/40134444?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Aniket Banyal</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=dummy26" title="Documentation">📖</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=dummy26" title="Code">💻</a></td>
  </tr>
  <tr>
    <td align="center"><a href="https://github.com/AnkanDas22"><img src="https://avatars1.githubusercontent.com/u/30185594?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Ankan Das</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=AnkanDas22" title="Documentation">📖</a></td>
    <td align="center"><a href="https://anshu-jindal.github.io/portfolio1/"><img src="https://avatars.githubusercontent.com/u/62394488?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Anshu Jindal</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=Anshu-jindal" title="Documentation">📖</a></td>
    <td align="center"><a href="https://github.com/PyDrummer"><img src="https://avatars.githubusercontent.com/u/62918152?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Anthony B.</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=PyDrummer" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/anurag629"><img src="https://avatars.githubusercontent.com/u/78868769?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Anurag verma</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=anurag629" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/znhv"><img src="https://avatars.githubusercontent.com/u/14875990?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Boris Zhenikhov</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=znhv" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/BrianPainter"><img src="https://avatars2.githubusercontent.com/u/1342663?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Brian Painter</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=BrianPainter" title="Code">💻</a></td>
    <td align="center"><a href="https://bryliechristopheroxley.info"><img src="https://avatars1.githubusercontent.com/u/17307?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Brylie Christopher Oxley</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=brylie" title="Code">💻</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/issues?q=author%3Abrylie" title="Bug reports">🐛</a> <a href="#projectManagement-brylie" title="Project Management">📆</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/pulls?q=is%3Apr+reviewed-by%3Abrylie" title="Reviewed Pull Requests">👀</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=brylie" title="Documentation">📖</a> <a href="#infra-brylie" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a> <a href="#maintenance-brylie" title="Maintenance">🚧</a></td>
  </tr>
  <tr>
    <td align="center"><a href="https://github.com/CaioSR"><img src="https://avatars1.githubusercontent.com/u/26325211?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Caio Shimada Rabello</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=CaioSR" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/dborstelmann"><img src="https://avatars1.githubusercontent.com/u/6558873?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Dan Borstelmann</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=dborstelmann" title="Code">💻</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/issues?q=author%3Adborstelmann" title="Bug reports">🐛</a> <a href="#infra-dborstelmann" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a> <a href="#ideas-dborstelmann" title="Ideas, Planning, & Feedback">🤔</a></td>
    <td align="center"><a href="https://github.com/danielgrijalva"><img src="https://avatars1.githubusercontent.com/u/11547406?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Daniel Grijalva</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=danielgrijalva" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/dlarner3194"><img src="https://avatars2.githubusercontent.com/u/17296992?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Daniel Larner</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=dlarner3194" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/darcymeyer"><img src="https://avatars2.githubusercontent.com/u/15186598?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Darcy Meyer</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=darcymeyer" title="Code">💻</a></td>
    <td align="center"><a href="https://github.com/DCalliet"><img src="https://avatars0.githubusercontent.com/u/6856645?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Darius Calliet</b></sub></a><br /><a href="https://github.com/CiviWiki/OpenCiviWiki/commits?author=DCalliet" title="Code">💻</a> <a href="https://github.com/CiviWiki/OpenCiviWiki/issues?q=author%3ADCalliet" title="Bug reports">🐛</a> <a href="#ideas-DCalliet" title="Ideas, Planning, & Feedback">🤔</a></td>
    <td align="center"><a href="https://github.com/Di-re [...]

2021-10-15 09:51 UTC, brylie commented
Closing this pull request as it is continued in #1141 with attribution given to @Saatvat

2021-10-15 09:51 UTC, closed without merging

2021-10-15 10:41 UTC, sg-007 commented
> Closing this pull request as it is continued in #1141 with attribution given to @Saatvat

How will the commits be merged?

2021-10-15 10:45 UTC, brylie commented
The commits contained a lot of unrelated code, so had to be discarded. I have created a new commit and added you as a co-author for attribution.