media file
CiviWiki/OpenCiviWiki pull request #1205
Opened 2021-11-18 12:03 UTC by topguns837

Closes #1192
  
## Description

I have added the media directory . The code related to the addition of a media directory were already present in setting.py and urls.py . I have commented out a line in .gitignore due to which I was not able to able to add the media folder to the git repo.

2021-11-18 17:42 UTC, gorkemarslan requested changes

2021-11-18 17:42 UTC, gorkemarslan commented on .gitignore
> +#media/
Could you delete the commented line?

2021-11-18 17:44 UTC, topguns837 commented on .gitignore
> +#media/
ok

2021-11-18 18:05 UTC, gorkemarslan requested changes

2021-11-18 18:05 UTC, gorkemarslan commented on .gitignore
> -media/
People should not commit the content of the media folder so you should add:
`/project/media/*`

But that will ignore `.gitkeep` file.

So you should also set the `.gitignore` file such that it ignores the content of `media` folder except for `.gitkeep` file. You can look at what is done for `staticfiles` folder in `.gitignore` for this purpose.

2021-11-19 12:55 UTC, gorkemarslan requested changes

2021-11-19 12:55 UTC, gorkemarslan commented on .gitignore
> +>>>>>>> 6cbece5ae023814e69a4ef3868ff8e0691e5fcde
Apparently, you somehow include commit numbers in your commit. Could you remove them and make the file cleaner?

2021-11-26 09:33 UTC, brylie commented on .gitignore
> +>>>>>>>
Remove conflict annotations

2021-12-21 17:20 UTC, closed without merging