👌 IMPROVE: Create a functional landing page.
CiviWiki/OpenCiviWiki pull request #1420
Opened 2022-10-07 13:53 UTC by ApoorvaKashyap

Closes #1310 
  
## Description

This is a basic functional landing page, similar in function to the one displayed in the issue. 

Here's a look:
![landing](https://user-images.githubusercontent.com/30412013/194570045-9d0d7476-290d-4cd3-a548-ec5ffa8f6922.png)

2022-10-07 16:12 UTC, brylie requested changes
Let's ensure the UI texts can be translated by adding the `translate` tag to all English texts as was present on the previous home page.

Let's keep the markup clean by removing the line and double-line breaks.

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                CiviWiki is a non-profit community working to develop a democratic engagement web system.
Add `translate` tag here
```suggestion
                {% translate "CiviWiki is a non-profit community working to develop a democratic engagement web system." %}
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                discuss the problems they face, discover solutions, and enact change.
Add `blocktranslate` tag here.
```suggestion
                {% blocktranslate %}
                At CiviWiki we believe democracy works best when citizens are educated on issues and participate in the
                democratic process.
                We are a non-profit, non-partisan, community; working to build an open-source platform where citizens
                discuss the problems they face, discover solutions, and enact change.
                {% endblocktranslate %}
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                Check out our short video describing CiviWiki...
Add `translate` tag here.
```suggestion
                {% translate "Check out our short video describing CiviWiki..." %}
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +            <p class="small-text">Video made by
Add `translate` tag here.
```suggestion
            <p class="small-text">{% translate "Video made by" %}
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +            <h1 class="title">Why CiviWiki?</h1>
```suggestion
            <h1 class="title">{% translate "Why CiviWiki?"%}</h1>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                            and reserves space for dissenting opinions.
Let's use `p` tags and the `translate` template tag here.
```suggestion
                        <div class="text">
                            <p>{% translate "As the name CiviWiki implies, our core content will be contributed by volunteers on our Wiki." %}</p>
                            <p>{% translate "Our topic format is modular." %}</p>
                            <p> {% translate "The structure allows a community of volunteers to collaborate on a single political issue and reserves space for dissenting opinions." %}</p>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                        <h2 class="subtitle">Democratically Contributed Media</h2>
```suggestion
                        <h2 class="subtitle">{% translate "Democratically Contributed Media" %}</h2>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                        </div><br><br>
```suggestion
                        </div>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                    <td><h2 class="subtitle">Personalized Policy Feed</h2>
```suggestion
                    <td><h2 class="subtitle">{% translate "Personalized Policy Feed" %}</h2>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                        content.</div><br><br>
```suggestion
                        <p>{% translate "CiviWiki intelligently personalizes users' feeds in two meaningful ways." %}</p>
                        <p>{% translate "First, the issues promoted to users' feeds will be personalized to the user's expressed interests and the timeliness of the issue." %}</p>
                        <p>{% translate "Second, the structure of the issue topics break policy positions into bite-sized
                        contentions we call Civies. Each Civi is logically related to the rest of the topic. Based on
                        the user's support, opposition, or neutrality to each Civi, CiviWiki promotes different relevant
                        content." %}</p>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                </tr>
Let's remove this section since it is no longer relevant to the project.
```suggestion
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +            <p>See what your voice can bring to your community!</p><br><br><a href="/login/"><button class="ripple">Join CiviWiki</button></a>
We want to use block elements for layout. What happens if we apply the ripple class directly to the anchor tag?

```suggestion
            <p>{% translate "See what your voice can bring to your community!" %}</p><a href="/login/"><button class="ripple">Join CiviWiki</button></a>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +            <p class="text">CiviWiki is still in development!</p><br><br>
Add translate, remove line breaks.

```suggestion
            <p class="text">{% translate "CiviWiki is still in development!" %}</p>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +            <a href="/login/"><button class="ripple">Register</button></a><span class="text">&</span><a href="/support_us/"><button class="ripple">Support Us</button></div><br><br>
Add translate
```suggestion
            <a href="/login/">
                <button class="ripple">{% translate "Register" %}</button></a>
                &
                <a href="/support_us/"><button class="ripple">{% translate "Support Us" %}</button></div>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                <th>Connect With Us</th>
```suggestion
                <th>{% translate "Connect With Us" %}</th>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                <td><a class="body-link" href="mailto:mitchell@civiwiki.org" target="_blank">Email</a></td>
```suggestion
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                <td><a class="body-link" href="https://github.com/CiviWiki/OpenCiviWiki/issues" target="_blank">Open Issues</a></td>
```suggestion
                <td><a class="body-link" href="https://github.com/CiviWiki/OpenCiviWiki/issues" target="_blank">{% translate "Open Issues" %}</a></td>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                <td><a class="body-link" href="https://waffle.io/CiviWiki/OpenCiviWiki" target="_blank" rel="noopener noreferrer">Development Roadmap</a></td>
```suggestion
                <td><a class="body-link" href="https://waffle.io/CiviWiki/OpenCiviWiki" target="_blank" rel="noopener noreferrer">{% translate "Development Roadmap" %}</a></td>
```

2022-10-07 16:12 UTC, brylie commented on project/core/templates/landing.html
> +                <td><a class="body-link" href="https://riot.im/app/#/room/#CiviWiki:matrix.org" target="_blank" rel="noopener noreferrer">Live Chat on Matrix</a></td>
```suggestion
                <td><a class="body-link" href="https://riot.im/app/#/room/#CiviWiki:matrix.org" target="_blank" rel="noopener noreferrer">{% translate "Live Chat on Matrix" %}</a></td>
```

2022-10-08 07:49 UTC, gorkemarslan requested changes

2022-10-08 07:49 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +  } */
```suggestion
```

2022-10-08 07:49 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +    /* box-shadow: 0 0 4px #999; */
```suggestion
```

2022-10-08 07:49 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +    /* border-right: 2px solid rgba(136, 16, 184, 0.75); */
```suggestion
```

2022-10-08 07:49 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +    /* transform: translateY(-50%); */
```suggestion
```

2022-10-08 07:49 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +      /* padding: 2em; */
```suggestion
```

2022-10-08 07:52 UTC, gorkemarslan requested changes

2022-10-08 07:52 UTC, gorkemarslan commented on project/core/templates/static/less/landing.css
> +    overflow:hidden;
Could you use an online CSS beautifier tool to format the whole file?

2022-10-09 10:06 UTC, brylie requested changes

2022-10-09 10:06 UTC, brylie commented on project/core/templates/static/less/landing.css
> +  }
Add a new line at the end of files :-)
```suggestion
  }
  
```

2022-10-14 06:32 UTC, brylie commented
@ApoorvaKashyap, will you be able to address any of the pull request review comments so we can merge this work into CiviWiki `develop`?

2022-10-15 14:46 UTC, ApoorvaKashyap commented
Hi
I'm not getting enough time to work on this at the moment. Perhaps someone else can take over.

2022-11-12 23:39 UTC, rdhoge commented
Hi Brylie,

I have been following this project for a few months.  I would try to make a contribution.  I noticed there are requested changes to this pull request that do not seem to have been completed.  If you would like, I would be willing to incorporate the requested changes to try to help move this along.

2022-11-18 06:58 UTC, closed without merging