Port templates in core to Django templating syntax
CiviWiki/OpenCiviWiki pull request #1494
Opened 2023-01-31 10:26 UTC by Nehemiah60

Closes #1405
  
## Description
Implemented Django templating syntax for all the templates in the core app

2023-02-01 17:18 UTC, brylie requested changes
Make sure there is only one `{% block content %}` in each template HTML file.

Any Backbone.js template needs to be converted to Django template syntax.

2023-02-08 15:19 UTC, brylie commented on project/core/templates/about.html
> +{% block content %}
This should be the end of the content block.
```suggestion
{% endblock content %}
```

2023-02-08 15:20 UTC, brylie commented on project/core/templates/email/base_email_template.html
> +{%block content%}
We don't need these blocks for the email template.
```suggestion
```

2023-02-08 15:20 UTC, brylie commented on project/core/templates/email/base_email_template.html
> +
```suggestion
```

2023-02-08 15:21 UTC, brylie commented on project/core/templates/global_nav.html
> +{%block content%}
Since this is a template partial, we don't need any of these tags.
```suggestion
```

2023-02-08 15:22 UTC, brylie commented on project/core/templates/global_nav.html
> +{%endblock content%}
```suggestion
```

2023-02-08 15:23 UTC, brylie commented on project/core/templates/landing.html
> +{%block content%}
Since this doesn't extend from `base.html`, we don't need to define the content block.
```suggestion
```

2023-02-08 15:23 UTC, brylie commented on project/core/templates/landing.html
> +{%endblock content%}
```suggestion
```

2023-02-08 15:24 UTC, brylie commented on project/core/templates/partials/notifications/notification_base.html
> +{% block content %}
We don't need block content since we're not inheriting from `base.html`
```suggestion
```

2023-02-08 15:24 UTC, brylie commented on project/core/templates/partials/notifications/notification_base.html
> +{% endblock content %}
```suggestion
```

2023-02-08 15:24 UTC, brylie commented on project/core/templates/partials/notifications/notification_item.html
> +{% block content %}
This is a partial template, it's not inheriting from `base.html`
```suggestion
```

2023-02-08 15:24 UTC, brylie commented on project/core/templates/partials/notifications/notification_item.html
> +{% endblock content%}
```suggestion
```

2023-02-08 15:25 UTC, brylie requested changes
If a template doesn't extend `base.htm`, we don't need to add the `block content`. Please remove `block content` and `endblock content` from all files that don't extend `base.html`.

2023-02-08 15:26 UTC, brylie commented on project/core/templates/global_nav.html
> +{%endblock content%}
```suggestion
```

2023-02-08 15:27 UTC, brylie commented on project/core/templates/partials/notifications/notification_base.html
> +{% endblock content %}
```suggestion
```

2023-02-08 15:27 UTC, brylie commented on project/core/templates/partials/notifications/notification_item.html
> +{% endblock content%}
```suggestion
```

2023-02-08 15:27 UTC, brylie commented on project/core/templates/static_footer.html
> +{%block content%}
```suggestion
```

2023-02-08 15:27 UTC, brylie commented on project/core/templates/static_footer.html
> +{%endblock content%}
```suggestion
```

2023-02-08 15:28 UTC, brylie commented on project/core/templates/static_nav.html
> +{%block content%}
```suggestion
```

2023-02-08 15:28 UTC, brylie commented on project/core/templates/static_nav.html
> +{%endblock content%}
```suggestion
```

2023-02-10 16:10 UTC, brylie requested changes

2023-02-10 16:10 UTC, brylie commented on project/core/templates/base.html
> -
The base.html template needs to define the content block so child templates can insert content into that block. Please restore the content block in this file.

2023-02-10 17:34 UTC, Nehemiah60 commented on project/core/templates/base.html
> -
I hope all the other templates are good @brylie

2023-02-11 11:33 UTC, brylie requested changes

2023-02-11 11:33 UTC, brylie commented on project/core/templates/about.html
> +{% block content %}
Move this block definition to line 12, after the page_title block

2023-02-11 11:34 UTC, brylie commented on project/core/templates/about.html
> +
```suggestion
{% block content %}
```

2023-02-11 16:59 UTC, brylie approved these changes

2023-02-11 16:59 UTC, merged