Add a default parameter to the get_env_variable function
CiviWiki/OpenCiviWiki pull request #772
Opened 2020-10-02 12:42 UTC by BrianPainter

Allow users to set defaults in the settings.py file for any items they are getting from an environment variable. Useful to have sane defaults if environment variables are not set.

2020-10-02 14:46 UTC, brylie requested changes
I'm just wondering whether we should be using `os.getenv()` instead of this bespoke function.

2020-10-03 14:49 UTC, BrianPainter commented
Are you opposed to an additional package: "django-environ"? It uses os.environ to read environment variables, and has two additional features: 1) includes same functionality as dj_database_url 2) allows user to optionally create .env file containing the environment variables they wish to use (easy to set environment variables for development).

2020-10-04 07:37 UTC, brylie commented
Django-environ sounds fine.

2020-10-05 03:02 UTC, BrianPainter commented
Included as part of #778

2020-10-05 03:02 UTC, closed without merging