new: remove closed beta and invitation functionality #859
CiviWiki/OpenCiviWiki pull request #861
Opened 2021-04-25 15:25 UTC by jithenshriyan

Remove: closed beta and invitation functionality.

Closes #849.

Changes proposed in this pull request:

Remove Beta_Blocker function and decorator from custom_decorators.py and views.py
Remove HTML files for closed beta features
Remove functions and settings for closed beta features

Sorry about the last two PRs I had opened and closed. I had chosen your base repository as master and saw there were 10,000 changes. I figured out I need to choose develop as the base repo. Let me know if there's anything else. Thanks!

2021-04-25 15:25 UTC, pep8speaks commented
Hello @jithenshriyan! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`project/frontend_views/urls.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/6d02f8487b581cee232da271464a73822e40835c/project/frontend_views/urls.py):

> [Line 16:121](https://github.com/CiviWiki/OpenCiviWiki/blob/6d02f8487b581cee232da271464a73822e40835c/project/frontend_views/urls.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 120 characters)

2021-04-25 15:59 UTC, brylie commented
Thanks. We will need to make a database migration for this pull request. Are you able to successfully run the command `python manage.py makemigrations` on your branch? If not, I can help.

2021-04-25 16:25 UTC, jithenshriyan commented
Sure, I've installed PostgreSQL, Redis, and a virtual environment.  

I'm getting an error when running `pip install -r requirements.txt`. It's installed some of the packages but not all of them.

`ERROR: Could not find a version that satisfies the requirement psycopg2==2.8.6`
`ERROR: No matching distribution found for psycopg2==2.8.6`

Do I need to change the versions labeled to the latest ones in order for pip to install them?

Also, once I've completed that, how do I create the environment variables on Mac and finally populate the database?

Thanks!

2021-04-26 07:23 UTC, brylie commented
Psycopg2 2.8.6 is a valid release (and installs in my virtual environment):

https://www.psycopg.org/articles/2020/09/06/psycopg-286-released/

Are you installing the requirements globally or in a virtual environment?

2021-04-26 15:07 UTC, jithenshriyan commented
I'm installing everything locally and I believe it's on my virtual env.

I have the following already setup:
- Virtual Env
- Some of the requirements (Others coming as failures)
- Local Postgre Database

I'm stuck at the requirements file and environment variables.

Is it fine if I make the changes without having to set up all the databases and users? I won't be using it after, and I've tried setting up everything but it didn't work.

Thanks.

2021-04-26 19:51 UTC, jithenshriyan commented
I was able to get docker setup on my computer and it was so much easier to set up other projects. 

When setting this project up on Docker, there was an error with your requirements.txt file.

` > [11/13] RUN pip install -r requirements.txt:                                 
#15 1.370 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
`

If we're able to get this fixed, then the entire project will be set up on my computer and I can fix the PR.

2021-04-27 08:03 UTC, brylie commented
I was suspecting that Python 2 was the issue. We should now be targeting Python 3.7+. I'll create an issue to make sure we are not specifying Python 2 anywhere. Also, the main goal of the current release is to remove many dependencies, to the point where even Docker should be unnecessary unless it is desirable to use Postgres for local development.

2021-04-27 08:06 UTC, brylie commented
I created an issue to clean up the Dockerfile https://github.com/CiviWiki/OpenCiviWiki/issues/865

2021-05-13 08:36 UTC, brylie requested changes

2021-05-13 08:36 UTC, brylie commented on project/authentication/authentication.py
> +                account.beta_access = True
Let's remove this field entirely, since there will no longer be a `beta_access` field in the `Account` model.

2021-05-13 08:36 UTC, brylie commented on project/frontend_views/urls.py
> +        v.beta_register, name='beta_register'),
We can remove these routes

2021-05-13 08:38 UTC, brylie requested changes

2021-05-13 08:38 UTC, brylie commented on project/api/models/account.py
> -    beta_access = models.BooleanField(default=False)
:warning: **Note** Remember to run the [`makemigrations` command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#django-admin-makemigrations) after changing model fields.

2021-05-14 18:14 UTC, jithenshriyan commented
Got it. Has the Docker issue been fixed? If so, I can get it set up quickly on my computer and make the changes.

2021-05-15 08:06 UTC, brylie commented
@jithenshriyan yes, we just merged an improved Dockerfile. :-)

2021-06-01 07:55 UTC, brylie commented
@jithenshriyan please let me know your status with this issue. I'm available to help resolve any issues you might be facing.

2021-06-14 08:48 UTC, brylie commented
@jithenshriyan are you able to create the migrations now? This pull request looks great overall!

2021-06-14 08:52 UTC, brylie commented
@all-contributors please add @jithenshriyan for code

@jithenshriyan I'm adding you as a code contributor for your efforts, even though we haven't been able to merge them yet :-)

2021-09-14 08:34 UTC, brylie commented
Closing, since this work has been completed.

2021-09-14 08:34 UTC, closed without merging