Issue #926 fixed
CiviWiki/OpenCiviWiki pull request #955
Opened 2021-07-19 16:43 UTC by skattel49

I have fixed copied the Accounts model to ./accounts/model.py and changed it's name to Profile as instructed

2021-07-19 16:43 UTC, pep8speaks commented
Hello @skattel49! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`project/accounts/models.py`](https://github.com/CiviWiki/OpenCiviWiki/blob/df6e234d2d545a4ebe7aad92bea4b1036e1ebd3d/project/accounts/models.py):

> [Line 13:1](https://github.com/CiviWiki/OpenCiviWiki/blob/df6e234d2d545a4ebe7aad92bea4b1036e1ebd3d/project/accounts/models.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-07-19 16:49 UTC, brylie requested changes

2021-07-19 16:49 UTC, brylie commented on project/accounts/models.py
> +        )
Let's use f-strings here

```suggestion
        full_name = f"{ self.first_name } { self.last_name }"
```

2021-07-19 17:03 UTC, skattel49 commented
I have changed the string formatting to f-strings as suggested.

2021-07-20 09:50 UTC, brylie approved these changes

2021-07-20 09:50 UTC, brylie requested changes
This looks good.

Remember to run the command `python manage.py makemigrations` and commit the migrations to this branch.

2021-09-01 09:26 UTC, brylie commented
@skattel49, please remember to run `python manage.py makemigrations` and commit the migration file to this branch. Any changes to a model need to have accompanying migration(s).

2021-09-14 08:34 UTC, brylie commented
These changes were merged in a separate pull request in order for me to make changes to the branch.

2021-09-14 08:34 UTC, closed without merging